class PlayerInformation{
    constructor(name, run, ball , wicket, over, imageUrl, dedicatedGroup){
        this.name = name;
        this.run = run;
        this.ball = ball;
        this.wicket = wicket;
        this.over = over;
        this.imageUrl = imageUrl;
        this.dedicatedGroup = dedicatedGroup;
    }
}

let playerInformation = [
    {
        "name":"Baten",
        "run":0,
        "ball":0,
        "wicket":0,
        "over": 0,
        "imageUrl": "images/baten.jpg",
        "dedicatedGroup": "Baten",
    },
    {
        "name":"Asif",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/asif.jpg",
        "dedicatedGroup": "Baten",
    },
    {
        "name":"Latif",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Baten",
    },
    {
        "name":"Anamul",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Baten",
    },
    {
        "name":"Tariqul",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Baten",
    },
    {
        "name":"Ashraful",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Baten",
    },
    {
        "name":"Noman",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Baten",
    },
    {
        "name":"Roni",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Baten",
    },
    {
        "name":"Aminur",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Baten",
    },
    {
        "name":"Ebrahim",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Baten",
    },
    {
        "name":"Washim",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Baten",
    },
    {
        "name":"Shafiqul",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Baten",
    },
    {
        "name":"Shipu",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Baten",
    },
    {
        "name":"Shahin",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Shahin",
    },
    {
        "name":"Jahidul",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Shahin",
    },
    {
        "name":"Shamim(1)",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Shahin",
    },
    {
        "name":"Sajib",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Shahin",
    },
    {
        "name":"Shahinur",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Shahin",
    },
    {
        "name":"Atiqur",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Shahin",
    },
    {
        "name":"Srabon",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Shahin",
    },
    {
        "name":"Mamun",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Shahin",
    },
    {
        "name":"Hamid",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Shahin",
    },
    {
        "name":"Rasel(1)",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Shahin",
    },
    {
        "name":"Rasel(2)",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Shahin",
    },
    {
        "name":"Sajal",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Shahin",
    },
    {
        "name":"Tapos",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Shahin",
    },
    {
        "name":"Rajib",
        "run":8,
        "ball":45,
        "wicket": 0,
        "over": 2,
        "imageUrl": "images/rajib.jpg",
        "dedicatedGroup": "Rajib",
    },
    {
        "name":"Shakil",
        "run":4,
        "ball":18,
        "wicket": 1,
        "over": 1,
        "imageUrl": "images/shakil.jpg",
        "dedicatedGroup": "Rajib",
    },
    {
        "name":"Arif",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rajib",
    },
    {
        "name":"Shamim(2)",
        "run":0,
        "ball":3,
        "wicket": 1,
        "over": 1,
        "imageUrl": "images/shamim2.jpg",
        "dedicatedGroup": "Rajib",
    },
    {
        "name":"Selim",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rajib",
    },
    {
        "name":"Habibur",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rajib",
    },
    {
        "name":"Shahed",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rajib",
    },
    {
        "name":"Sumon",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rajib",
    },
    {
        "name":"Abdullah",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rajib",
    },
    {
        "name":"Shohag",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rajib",
    },
    {
        "name":"Kohinur",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rajib",
    },
    {
        "name":"Mamun(Emam Saheb)",
        "run":0,
        "ball":16,
        "wicket": 1,
        "over": 2,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rajib",
    },
    {
        "name":"Bijoy",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rajib",
    },
    {
        "name":"Rubel",
        "run":4,
        "ball":6,
        "wicket": 0,
        "over": 3,
        "imageUrl": "images/rubel.jpg",
        "dedicatedGroup": "Rubel",
    },
    {
        "name":"Parvez",
        "run":4,
        "ball":8,
        "wicket": 0,
        "over": 3,
        "imageUrl": "images/parvez.jpg",
        "dedicatedGroup": "Rubel",
    },
    {
        "name":"Emran",
        "run":0,
        "ball":8,
        "wicket": 0,
        "over": 3,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rubel",
    },
    {
        "name":"Joni",
        "run":8,
        "ball":16,
        "wicket": 1,
        "over": 2,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rubel",
    },
    {
        "name":"Dulal",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rubel",
    },
    {
        "name":"Forhad",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rubel",
    },
    {
        "name":"Sharif",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rubel",
    },
    {
        "name":"Emon",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rubel",
    },
    {
        "name":"Mukles",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rubel",
    },
    {
        "name":"Novin",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rubel",
    },
    {
        "name":"Minhaj",
        "run":0,
        "ball":2,
        "wicket": 1,
        "over": 2,
        "imageUrl": "images/minhaj.jpg",
        "dedicatedGroup": "Rubel",
    },
    {
        "name":"Masum",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rubel",
    },
    {
        "name":"Noyon",
        "run":0,
        "ball":0,
        "wicket": 0,
        "over": 0,
        "imageUrl": "images/avatar.jpg",
        "dedicatedGroup": "Rubel",
    },

];